import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './theme-config.css'
import './globals.css'
import Navbar from './Navbar'
import '@radix-ui/themes/styles.css';
import { Container, Theme, ThemePanel } from '@radix-ui/themes';
import AuthProvider from './auth/AuthProvider'

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        {/* <Theme appearance="light" radius="full"> */}
        <AuthProvider>
        <Theme>
        <Navbar />  
        <Container>
        {children}
        </Container>
        {/* <ThemePanel /> */}
        </Theme>
        </AuthProvider>
      </body>
    </html>
  )
}
